//using System;
//using System.Collections.Generic;
//using System.Text;
//using System.Runtime.Serialization;
//using Newtonsoft.Json;

//namespace WeatherDesktopSharedCore.Interfaces
//{
//    public class YahooWeather : BaseWeather
//    {
//        const string Yahoo_Weather_Url = "https://query.yahooapis.com/v1/public/yql?q=select%20item.condition%2C%20item.description%20from%20weather.forecast(1)%20where%20woeid%20in%20(select%20content%20from%20pm.location.zip.region(1)%20where%20zip%3D%22{0}%22%20and%20region%3D%22us%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&callback=";
//        const string APIKey = "";

//        private Boolean _Success;
//        private int _Temp;
//        private string _err = string.Empty;
//        private string _forcast;
//        private WeatherTypes _type;
//        private string _url;
//        public override string ToString()
//        {
//            return "Yahoo Weather";
//        }
//        public override string ErrorMessages() { return _err; }
//        public override string ForcastDescription() { return _forcast; }
//        public override bool Success() { return _Success; }
//        public override int Temp() { return _Temp; }
//        public override WeatherTypes WType() { return _type; }
//        public override string PostUrl()
//        {
//            return _url;
//        }


//        public override void Invoke()
//        {
//            try {

//                YahooWeatherObject result = LiveCall();
//                _Temp = int.Parse(result.query.results.channel.item.condition.temp);
//                _forcast = RemoveMarkup(result.query.results.channel.item.description);
//              _type = GetWeatherType(int.Parse(result.query.results.channel.item.condition.code));

//                _Success = true;
//            }
//            catch (Exception x) {

//                _err = x.ToString(); _Success = false;
//            }
//        }




//        WeatherTypes GetWeatherType(int code)
//        {
//            switch (code)
//            {
//                case 31:
//                case 32:
//                case 33:
//                case 34:
//                    return WeatherTypes.Clear;
//                case 26:
//                case 27:
//                case 28:
//                    return WeatherTypes.Cloudy;
//                case 19:
//                    return WeatherTypes.Dust;
//                case 20:
//                    return WeatherTypes.Fog;
//                case 25:
//                    return WeatherTypes.Frigid;
//                case 21:
//                    return WeatherTypes.Haze;
//                case 36:
//                    return WeatherTypes.Hot;
//                case 29:
//                case 30:
//                case 44:
//                    return WeatherTypes.PartlyCloudy;
//                case 5:
//                case 6:
//                case 8:
//                case 9:
//                case 10:
//                case 11:
//                case 12:
//                case 17:
//                case 18:
//                case 35:
//                case 40:
//                    return WeatherTypes.Rain;
//                case 22:
//                    return WeatherTypes.Smoke;
//                case 7:
//                case 13:
//                case 14:
//                case 15:
//                case 16:
//                case 41:
//                case 42:
//                case 43:
//                case 46:
//                    return WeatherTypes.Snow;
//                case 23:
//                case 24:
//                    return WeatherTypes.Windy;
//                case 3:
//                case 4:
//                case 37:
//                case 38:
//                case 39:
//                case 45:
//                case 47:
//                default:
//                    return WeatherTypes.ThunderStorm;
//            }

//        }

//                private static string RemoveMarkup(string MarkedupHTML)
//        {
//            return System.Text.RegularExpressions.Regex.Replace(MarkedupHTML, "<.*?>", String.Empty);
//        }
//        YahooWeatherObject LiveCall()
//        {
//            string results = string.Empty;
//            string URL = string.Empty;
//            YahooWeatherObject Response = new YahooWeatherObject();
//            URL = string.Format(Yahoo_Weather_Url, ZipCode);
//            _url = URL;
//            results = CompressedCallSite(URL);
//            Response = JsonConvert.DeserializeObject<YahooWeatherObject>(results);
//            return Response;
//        }


//        #region Autogenerated code

//        [DataContract]
//        public class Condition
//        {

//            [DataMember(Name = "code")]
//            public string code { get; set; }

//            [DataMember(Name = "date")]
//            public string date { get; set; }

//            [DataMember(Name = "temp")]
//            public string temp { get; set; }

//            [DataMember(Name = "text")]
//            public string text { get; set; }
//        }

//        [DataContract]
//        public class Item
//        {

//            [DataMember(Name = "condition")]
//            public Condition condition { get; set; }

//            [DataMember(Name = "description")]
//            public string description { get; set; }
//        }

//        [DataContract]
//        public class Channel
//        {

//            [DataMember(Name = "item")]
//            public Item item { get; set; }
//        }

//        [DataContract]
//        public class Results
//        {

//            [DataMember(Name = "channel")]
//            public Channel channel { get; set; }
//        }

//        [DataContract]
//        public class Query
//        {

//            [DataMember(Name = "count")]
//            public int count { get; set; }

//            [DataMember(Name = "created")]
//            public DateTime created { get; set; }

//            [DataMember(Name = "lang")]
//            public string lang { get; set; }

//            [DataMember(Name = "results")]
//            public Results results { get; set; }
//        }

//        [DataContract]
//        public class YahooWeatherObject
//        {

//            [DataMember(Name = "query")]
//            public Query query { get; set; }
//        }
//        #endregion
//    }
//}
